// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreCodeFirstFromDB.Models;

[Index("DeptId", Name = "IX_Employees_DeptId")]
public partial class Employee
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Age { get; set; }

    [Required]
    public string Email { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Salary { get; set; }

    [Required]
    public string Address { get; set; }

    public int? DeptId { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Employees")]
    public virtual Department Dept { get; set; }
}